### PR TITLE
doc: add LGPLv3 license

### LINKED ISSUE #18: Add an (Open Source) license?
The project lacks COPYING/LICENSE file.

### PR DESCRIPTION
**Pull request by c-dilks**
close #18

### CODE REVIEW

**Comment by alexander-kiselev** [comment]
Chris,

  what am I supposed to do with this request?

  Cheers,
    Alexander.

________________________________

**Comment by c-dilks** [comment]
Now that `irt` is a dependency of `EICrecon` and a part of the `eic-shell` container, it should have the usual software things like version numbering and a license/copyright.

For libraries, LGPL is a common choice, and this pull request proposes using GNU LPGLv3: https://choosealicense.com/licenses/gpl-3.0/

Since you wrote the code, it's your choice which license to use; https://choosealicense.com/ is a decent reference. Are you okay with LGPLv3, or do you prefer a different one?

**Comment by alexander-kiselev** [comment]
Hi Chris,

  sure I don't care. Have doubts we would ever be able to sell this code anyway 🙂 Just tell me where to click.

  Cheers,
    Alexander.

________________________________

**Comment by c-dilks** [comment]
Done, I took care of the clicking

**Comment by alexander-kiselev** [comment]
thanx!

________________________________

**Pull request merged**
